<a href="https://colab.research.google.com/github/clangdon1023/deep_learning_challenge/blob/main/Optimization%20Attempt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [15]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
revised = application_df.drop(columns=['EIN', 'NAME'])
revised

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [16]:
# Determine the number of unique values in each column.
revised.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [17]:
# Look at APPLICATION_TYPE value counts for binning
revised_binning = revised['APPLICATION_TYPE'].value_counts()
revised_binning

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [37]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(revised_binning[revised_binning < 5].index)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning
classification_counts = revised['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [101]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_repla
classifications_to_replace = list(classification_counts[classification_counts > 777].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

Other    34299
Name: CLASSIFICATION, dtype: int64

In [64]:
# Convert categorical data to numeric with `pd.get_dummies`
revised2 = pd.get_dummies(revised)
revised2.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [62]:
revised2 = revised.drop(columns=['SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'])
revised2.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [102]:
# Split our preprocessed data into our features and target arrays
x = revised2.drop(columns=['IS_SUCCESSFUL']).values
y = revised2['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(x, y)

In [103]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

**Compile, Train and Evaluate the Model**

In [116]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(x_train[0])
layer_1_nodes = 120
layer_2_nodes = 103
layer_3_nodes = 100




nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_1_nodes, input_dim=number_input_features, activation='sigmoid'))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_2_nodes, activation='relu'))
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_3_nodes, activation='sigmoid'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_91 (Dense)            (None, 120)               14040

 dense_92 (Dense)            (None, 103)               12463

 dense_93 (Dense)            (None, 100)               10400

 dense_94 (Dense)            (None, 1)                 101

=================================================================
Total params: 37004 (144.55 KB)
Trainable params: 37004 (144.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [117]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [118]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train, epochs=135)

Epoch 1/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5806 - accuracy: 0.7134
Epoch 2/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5601 - accuracy: 0.7272
Epoch 3/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5550 - accuracy: 0.7299
Epoch 4/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7306
Epoch 5/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7324
Epoch 6/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7341
Epoch 7/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7323
Epoch 8/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7318
Epoch 9/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7338
Epoch 10/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7340
Epoch 11/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7333
Epoch 12/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7330
Epoch 13/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7341
Epoch 14/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7345
Epoch 15/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7341
Epoch 16/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5432 - accuracy: 0.7345
Epoch 17/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7342
Epoch 18/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7361
Epoch 19/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7353
Epoch 20/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7353
Epoch 21/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5410 - accuracy: 0.7354
Epoch 22/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7361
Epoch 23/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7375
Epoch 24/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7366
Epoch 25/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 26/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7376
Epoch 27/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7376
Epoch 28/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5380 - accuracy: 0.7367
Epoch 29/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7369
Epoch 30/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 31/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7392
Epoch 32/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7373
Epoch 33/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 34/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7389
Epoch 35/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 36/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7407
Epoch 37/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7393
Epoch 38/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7386
Epoch 39/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7392
Epoch 40/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 41/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7390
Epoch 42/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 43/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 44/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7404
Epoch 45/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 46/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5325 - accuracy: 0.7407
Epoch 47/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7409
Epoch 48/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7407
Epoch 49/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7416
Epoch 50/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7418
Epoch 51/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7418
Epoch 52/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5311 - accuracy: 0.7402
Epoch 53/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7418
Epoch 54/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5307 - accuracy: 0.7423
Epoch 55/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5304 - accuracy: 0.7415
Epoch 56/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7411
Epoch 57/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5302 - accuracy: 0.7415
Epoch 58/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.7423
Epoch 59/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7412
Epoch 60/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7420
Epoch 61/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7420
Epoch 62/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7421
Epoch 63/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7412
Epoch 64/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7422
Epoch 65/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5292 - accuracy: 0.7429
Epoch 66/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5290 - accuracy: 0.7428
Epoch 67/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7427
Epoch 68/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7424
Epoch 69/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7431
Epoch 70/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5284 - accuracy: 0.7421
Epoch 71/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5279 - accuracy: 0.7425
Epoch 72/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5277 - accuracy: 0.7429
Epoch 73/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7424
Epoch 74/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7433
Epoch 75/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5274 - accuracy: 0.7423
Epoch 76/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5276 - accuracy: 0.7434
Epoch 77/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5273 - accuracy: 0.7425
Epoch 78/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7432
Epoch 79/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5267 - accuracy: 0.7422
Epoch 80/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5268 - accuracy: 0.7438
Epoch 81/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5266 - accuracy: 0.7425
Epoch 82/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7438
Epoch 83/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5261 - accuracy: 0.7448
Epoch 84/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5268 - accuracy: 0.7432
Epoch 85/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5266 - accuracy: 0.7429
Epoch 86/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5265 - accuracy: 0.7431
Epoch 87/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7435
Epoch 88/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7434
Epoch 89/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7434
Epoch 90/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5259 - accuracy: 0.7440
Epoch 91/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5256 - accuracy: 0.7435
Epoch 92/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7436
Epoch 93/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7432
Epoch 94/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5256 - accuracy: 0.7440
Epoch 95/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7446
Epoch 96/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5254 - accuracy: 0.7435
Epoch 97/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5254 - accuracy: 0.7444
Epoch 98/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7437
Epoch 99/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7440
Epoch 100/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7448
Epoch 101/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7441
Epoch 102/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7439
Epoch 103/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5248 - accuracy: 0.7447
Epoch 104/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5251 - accuracy: 0.7446
Epoch 105/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7439
Epoch 106/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7442
Epoch 107/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7439
Epoch 108/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7446
Epoch 109/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5249 - accuracy: 0.7442
Epoch 110/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5245 - accuracy: 0.7434
Epoch 111/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7453
Epoch 112/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7446
Epoch 113/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7446
Epoch 114/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7445
Epoch 115/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5245 - accuracy: 0.7447
Epoch 116/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5242 - accuracy: 0.7446
Epoch 117/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7444
Epoch 118/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7443
Epoch 119/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7448
Epoch 120/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7449
Epoch 121/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5240 - accuracy: 0.7451
Epoch 122/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5244 - accuracy: 0.7445
Epoch 123/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7444
Epoch 124/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7445
Epoch 125/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5242 - accuracy: 0.7451
Epoch 126/135
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7446
Epoch 127/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5238 - accuracy: 0.7448
Epoch 128/135
804/804 [==============================] - 3s 4ms/step - loss: 0.5240 - accuracy: 0.7449
Epoch 129/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5240 - accuracy: 0.7439
Epoch 130/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5238 - accuracy: 0.7451
Epoch 131/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5236 - accuracy: 0.7448
Epoch 132/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5238 - accuracy: 0.7448
Epoch 133/135
804/804 [==============================] - 3s 3ms/step - loss: 0.5239 - accuracy: 0.7446
Epoch 134/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5239 - accuracy: 0.7449
Epoch 135/135
804/804 [==============================] - 2s 3ms/step - loss: 0.5238 - accuracy: 0.7450

In [33]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5738 - accuracy: 0.7346 - 504ms/epoch - 2ms/step
Loss: 0.5738140940666199, Accuracy: 0.7345772385597229

In [36]:
# Export our model to HDF5 file
nn.save("charity_train.h5")